# This is a basic workflow to help you get started with Actions

name: Build Docker image

# Controls when the action will run. Triggers the workflow on publishing a new release or push to main
on:
  pull-request:
    branches: [ main ]
    paths-ignore:
      - '**.yml'
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build -t kafka-ssl
